require 'rubygems'
require 'hoe'
require File.expand_path(File.join(File.dirname(__FILE__), "/lib/multi_rails"))
load File.expand_path(File.join(File.dirname(__FILE__), "/tasks/multi_rails.rake"))

Hoe.new('multi_rails', MultiRails::VERSION) do |p|
  p.rubyforge_name = 'multi-rails'
  p.author = 'Relevance'
  p.email = 'multi_rails@googlegroups.com'
  p.summary = 'Testing tool to easily test agaist multiple versions of Rails.'
  p.description = p.paragraphs_of('README.txt', 0..10).join("\n\n")
  p.url = 'http://multi-rails.rubyforge.org/'
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.remote_rdoc_dir = '' # Release to root
  p.test_globs = 'test/**/*_test.rb' # we use the foo_test convention
  p.spec_extras[:require_paths] = ['lib', 'tasks']
end